//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team10_Banking_2WebApiPrioject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdminOtp
    {
        public string admin_id { get; set; }
        public int opt { get; set; }
        public string email_id { get; set; }
    
        public virtual tbladmin tbladmin { get; set; }
    }
}
