//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team10_Banking_2WebApiPrioject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBeneficiary
    {
        public int beneficiary_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> account_number { get; set; }
        public Nullable<int> beneficiary_account_number { get; set; }
        public string nickname { get; set; }
    
        public virtual tblBankingCustomer tblBankingCustomer { get; set; }
    }
}
