//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team10_Banking_2WebApiPrioject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransaction
    {
        public int transaction_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string transaction_type { get; set; }
        public Nullable<int> from_account { get; set; }
        public Nullable<int> to_account { get; set; }
        public Nullable<double> from_Account_balance { get; set; }
        public Nullable<double> to_Account_balance { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<System.DateTime> transaction_date { get; set; }
        public string remarks { get; set; }
    
        public virtual tblBankingCustomer tblBankingCustomer { get; set; }
    }
}
